
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class CreateChannelParameters {
    /**
    * Label: Channel Name, type: entry
    */
    String name
    /**
    * Label: Is Private, type: checkbox
    */
    boolean is_private
    /**
    * Label: User IDs, type: entry
    */
    String user_ids

    static CreateChannelParameters initParameters(StepParameters sp) {
        CreateChannelParameters parameters = new CreateChannelParameters()

        def name = sp.getRequiredParameter('name').value
        parameters.name = name
        def is_private = sp.getParameter('is_private').value == "true"
        parameters.is_private = is_private
        def user_ids = sp.getParameter('user_ids').value
        parameters.user_ids = user_ids

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: 166e232e5c260ba418cfcf183a604715 ===
