
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class SendRealtimeMessageParameters {
    /**
    * Label: Channel, type: entry
    */
    String channel
    /**
    * Label: Text, type: textarea
    */
    String text
    /**
    * Label: Blocks, type: textarea
    */
    String blocks

    static SendRealtimeMessageParameters initParameters(StepParameters sp) {
        SendRealtimeMessageParameters parameters = new SendRealtimeMessageParameters()

        def channel = sp.getRequiredParameter('channel').value
        parameters.channel = channel
        def text = sp.getRequiredParameter('text').value
        parameters.text = text
        def blocks = sp.getParameter('blocks').value
        parameters.blocks = blocks

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: d8d5d133f594a15480bcef3976d02a9a ===
